version: '3.4'

services:
  httplistenersimple:
    image: httplistenersimple
    build:
      context: .
      dockerfile: HTTPListenerSimple/Dockerfile

  requestsendersimple:
    image: ${DOCKER_REGISTRY}requestsendersimple
    build:
      context: .
      dockerfile: RequestSenderSimple/Dockerfile

