version: '3.4'

services:
  httplistenersimple:
    image: httplistenersimple
    build:
      context: .
      dockerfile: HTTPListenerSimple/Dockerfile
    expose:
      - "777"
    ports:
      - "777"

  requestsendersimple:
    image: requestsendersimple
    build:
      context: .
      dockerfile: RequestSenderSimple/Dockerfile