version: '3.4'

services:
  requestsendersimple:
    image: ${DOCKER_REGISTRY}requestsendersimple
    build:
      context: .
      dockerfile: RequestSenderSimple/Dockerfile
    depends_on:
      - httplistenersimple

  httplistenersimple:
    image: ${DOCKER_REGISTRY}httplistenersimple
    build:
      context: .
      dockerfile: HTTPListenerSimple/Dockerfile

